### ISSUE TITLE
Error when Accessing Customer Panel - "Currency code is required with currency style"

### ISSUE THREAD

**Issue by MineTech13** [stustapay/stustapay#393]
Hi team,

Firstly, I want to say that I'm enjoying using StustaPay. It seems like a fantastic solution so far! However, I encountered an issue when trying to access the customer panel. After entering the PIN, I receive the following error message:
```
Oops!
Sorry, an unexpected error has occurred.
Currency code is required with currency style.
```
I'm not sure if I've missed something during the installation process or if there's a setting I've overlooked. Could you please assist me in resolving this issue?

Thank you in advance for your help!

Best regards,
MineTech13 | Nils Z.

**Comment by mikonse** [comment]
Hi there,

from the error message I would guess that the currency is not configured correctly.
Can you share your event settings from the general tab and recheck that a proper currency is configured there?

**Comment by MineTech13** [comment]
Hi there,

Thanks for the quick response, and I apologize for the delay in getting back to you.

I’ve checked the event settings under the general tab, and it seems like the currency is configured correctly. Please see the screenshot below of my current event settings:

![image](https://github.com/stustapay/stustapay/assets/11505924/ecdb5da4-e546-48c1-9abd-829b383fbda6)

Could you please take a look and let me know if there’s anything I might be missing or if there’s another potential issue causing the error?

Thank you for your assistance!

Best regards,
MineTech13 | Nils Z.

**Comment by mikonse** [comment]
It's a bit hard to debug without more information.

Could provide the console error you are getting in the browser console when trying to access the customer portal?

What also might help me debug is if you could dump the whole event settings from the database.

Just run 
```bash
stustapay db attach
> select * from node;
> select * from event;
```
And paste the output here.

Also for reference: How did you install and setup the stustapay instance you are testing with?

**Comment by MineTech13** [comment]
Hi there,

Thank you for the follow-up.

I’ve gathered the requested information to help debug the issue.

**1. Browser Console Error:**
Please find the console error message below when trying to access the customer portal:
```
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
[NEU] Erläutern von Konsolenfehlern mithilfe von Copilot in Edge: Klicken Sie auf
         
         , um einen Fehler zu erklären.
        Weitere Informationen
        
          
          
          Nicht mehr anzeigen
        
main.e9f0635c170f92c3.js:74 i18next: languageChanged en-US
main.e9f0635c170f92c3.js:74 i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: 'translations', fallbackLng: Array(1), …}
main.e9f0635c170f92c3.js:1 
        
        
        GET https://cp.ssp.minescripts.me/api/config?base_url=https%3A%2F%2Fcp.ssp.minescripts.me 400 (Bad Request)
(anonym) @ main.e9f0635c170f92c3.js:1
ft @ main.e9f0635c170f92c3.js:1
(anonym) @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
ol @ main.e9f0635c170f92c3.js:154
Su @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
ku @ main.e9f0635c170f92c3.js:154
uu @ main.e9f0635c170f92c3.js:154
Uo @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
ku @ main.e9f0635c170f92c3.js:154
iu @ main.e9f0635c170f92c3.js:154
k @ main.e9f0635c170f92c3.js:154
T @ main.e9f0635c170f92c3.js:154
I.<computed> @ polyfills.1b8fad42747eb737.js:1
T @ polyfills.1b8fad42747eb737.js:1
L @ polyfills.1b8fad42747eb737.js:1
main.e9f0635c170f92c3.js:74  TypeError: Currency code is required with currency style.
    at new NumberFormat (<anonymous>)
    at main.e9f0635c170f92c3.js:154:44591
    at QO (main.e9f0635c170f92c3.js:154:65765)
    at Ea (main.e9f0635c170f92c3.js:154:392621)
    at Os (main.e9f0635c170f92c3.js:154:404252)
    at El (main.e9f0635c170f92c3.js:154:450343)
    at xu (main.e9f0635c170f92c3.js:154:438628)
    at yu (main.e9f0635c170f92c3.js:154:438556)
    at vu (main.e9f0635c170f92c3.js:154:438419)
    at uu (main.e9f0635c170f92c3.js:154:435560)
Jm @ main.e9f0635c170f92c3.js:74
Ea @ main.e9f0635c170f92c3.js:154
El @ main.e9f0635c170f92c3.js:154
xu @ main.e9f0635c170f92c3.js:154
yu @ main.e9f0635c170f92c3.js:154
vu @ main.e9f0635c170f92c3.js:154
uu @ main.e9f0635c170f92c3.js:154
Uo @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
main.e9f0635c170f92c3.js:74  TypeError: Currency code is required with currency style.
    at new NumberFormat (<anonymous>)
    at main.e9f0635c170f92c3.js:154:44591
    at QO (main.e9f0635c170f92c3.js:154:65765)
    at Ea (main.e9f0635c170f92c3.js:154:392621)
    at Os (main.e9f0635c170f92c3.js:154:404252)
    at El (main.e9f0635c170f92c3.js:154:450343)
    at xu (main.e9f0635c170f92c3.js:154:438628)
    at yu (main.e9f0635c170f92c3.js:154:438556)
    at vu (main.e9f0635c170f92c3.js:154:438419)
    at au (main.e9f0635c170f92c3.js:154:435226)
Jm @ main.e9f0635c170f92c3.js:74
Ea @ main.e9f0635c170f92c3.js:154
El @ main.e9f0635c170f92c3.js:154
xu @ main.e9f0635c170f92c3.js:154
yu @ main.e9f0635c170f92c3.js:154
vu @ main.e9f0635c170f92c3.js:154
au @ main.e9f0635c170f92c3.js:154
uu @ main.e9f0635c170f92c3.js:154
Uo @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
main.e9f0635c170f92c3.js:154  TypeError: Currency code is required with currency style.
    at new NumberFormat (<anonymous>)
    at main.e9f0635c170f92c3.js:154:44591
    at QO (main.e9f0635c170f92c3.js:154:65765)
    at Ea (main.e9f0635c170f92c3.js:154:392621)
    at Os (main.e9f0635c170f92c3.js:154:404252)
    at El (main.e9f0635c170f92c3.js:154:450343)
    at xu (main.e9f0635c170f92c3.js:154:438628)
    at yu (main.e9f0635c170f92c3.js:154:438556)
    at vu (main.e9f0635c170f92c3.js:154:438419)
    at au (main.e9f0635c170f92c3.js:154:435226)
fs @ main.e9f0635c170f92c3.js:154
i.componentDidCatch.n.callback @ main.e9f0635c170f92c3.js:154
zi @ main.e9f0635c170f92c3.js:154
wl @ main.e9f0635c170f92c3.js:154
xl @ main.e9f0635c170f92c3.js:154
xl @ main.e9f0635c170f92c3.js:154
bl @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
ku @ main.e9f0635c170f92c3.js:154
uu @ main.e9f0635c170f92c3.js:154
Uo @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
main.e9f0635c170f92c3.js:74  React Router caught the following error during render TypeError: Currency code is required with currency style.
    at new NumberFormat (<anonymous>)
    at main.e9f0635c170f92c3.js:154:44591
    at QO (main.e9f0635c170f92c3.js:154:65765)
    at Ea (main.e9f0635c170f92c3.js:154:392621)
    at Os (main.e9f0635c170f92c3.js:154:404252)
    at El (main.e9f0635c170f92c3.js:154:450343)
    at xu (main.e9f0635c170f92c3.js:154:438628)
    at yu (main.e9f0635c170f92c3.js:154:438556)
    at vu (main.e9f0635c170f92c3.js:154:438419)
    at au (main.e9f0635c170f92c3.js:154:435226) {componentStack: '\n    at QO (https://cp.ssp.minescripts.me/main.e9f…p.minescripts.me/main.e9f0635c170f92c3.js:1:5276)'}
componentDidCatch @ main.e9f0635c170f92c3.js:74
i.componentDidCatch.n.callback @ main.e9f0635c170f92c3.js:154
zi @ main.e9f0635c170f92c3.js:154
wl @ main.e9f0635c170f92c3.js:154
xl @ main.e9f0635c170f92c3.js:154
xl @ main.e9f0635c170f92c3.js:154
bl @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
ku @ main.e9f0635c170f92c3.js:154
uu @ main.e9f0635c170f92c3.js:154
Uo @ main.e9f0635c170f92c3.js:154
(anonym) @ main.e9f0635c170f92c3.js:154
```

**2. Event Settings from the Database:**
Here’s the output from running the SQL commands:

```sql
stustapay db attach
> select * from node;
```
```
 id | read_only | parent |     name      | description | event_id | path | parent_ids | event_node_id | parents_until_event_node
----+-----------+--------+---------------+-------------+----------+------+------------+---------------+--------------------------
  0 | f         |      0 | root          |             |          | /0   | {0}        |               |
  1 | f         |      0 | EventPay-Test |             |        0 | /0/1 | {0}        |             1 | {}
(2 rows)
```

```sql
> select * from event;
```
```
 id | currency_identifier | max_account_balance |       start_date       |        end_date        | daily_end_time |   ust_id    | bon_issuer |   bon_address    |    bon_title     | sumup_payment_enabled | sumup_affiliate_key | sumup_topup_enabled | sumup_api_key | sumup_merchant_code | customer_portal_url | customer_portal_about_page_url | customer_portal_data_privacy_url | customer_portal_contact_email | sepa_enabled |      sepa_sender_name       |      sepa_sender_iban       |          sepa_description           | sepa_max_num_payouts_in_run |                        sepa_allowed_country_codes                         | sumup_oauth_client_id | sumup_oauth_client_secret | sumup_oauth_refresh_token | email_enabled | email_default_sender | email_smtp_host | email_smtp_port | email_smtp_username | email_smtp_password |     payout_done_subject      |                                                                 payout_done_message                                                                 |     payout_registered_subject     |                                                                                                         payout_registered_message                                                                                                         | payout_sender
----+---------------------+---------------------+------------------------+------------------------+----------------+-------------+------------+------------------+------------------+-----------------------+---------------------+---------------------+---------------+---------------------+---------------------+--------------------------------+----------------------------------+-------------------------------+--------------+-----------------------------+-----------------------------+-------------------------------------+-----------------------------+---------------------------------------------------------------------------+-----------------------+---------------------------+---------------------------+---------------+----------------------+-----------------+-----------------+---------------------+---------------------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------
  0 | EUR                 |                 150 | 2024-06-01 13:00:00+00 | 2024-06-30 20:00:00+00 | 22:00:00       | DE123456789 | der verein | Müsterstraße 12 +| StuStaCulum 2023 | f                     |                     | f                   |               |                     |                     |                                |                                  | test-beschwerde@stustapay.de  | t            | Toller Festivalveranstalter | DE89 3704 0044 0532 0130 00 | FestivalName, TagID: {user_tag_uid} |                        1000 | {FI,AT,PT,BE,ES,CY,EE,FI,FR,DE,GR,IE,IT,LV,LT,LU,PT,MT,MC,NL,PT,SM,SK,SI} |                       |                           |                           | f             |                      |                 |                 |                     |                     | [StuStaPay] Payout Completed | Thank you for your patience. The payout process has been completed and the funds should arrive within the next days to your specified bank account. | [StuStaPay] Registered for Payout | Thank you for being part of our festival. Your remaining funds are registered for payout. They will be transferred to the specified bank account in our next manual payout. You will receive another email once we transferred the funds. |
    |                     |                     |                        |                        |                |             |            | 12398 Test Stadt |                  |                       |                     |                     |               |                     |                     |                                |                                  |                               |              |                             |                             |                                     |                             |                                                                           |                       |                           |                           |               |                      |                 |                 |                     |                     |                              |                                                                                                                                                     |                                   |                                                                                                                                                                                                                                           |
(1 row)
```

**3. Installation and Setup Details:**
I installed and set up the StustaPay instance using a custom Dockerfile script to containerize it. Please note that this script is a work in progress and not yet optimized for production. Below is the Dockerfile content:
(Addendum the Image i build with this file used this workflow run https://github.com/stustapay/stustapay/actions/runs/9373102553)
```Dockerfile
# Use the Debian Bookworm base image and name this stage "base"
FROM debian:bookworm as base

# Set default build arguments
ARG OWNER="stustapay"
ARG REPO="stustapay"
ARG WORKFLOW="84127321"
ARG PACKAGES="curl jq unzip ca-certificates python3 nginx"
ARG PERM_PACKAGES="python3 stustapay nginx"

# Update the package list
RUN apt update

# Install necessary packages without recommended additional packages
RUN apt install -y --no-install-recommends ${PACKAGES}

# Download and install stustapay
WORKDIR /tmp
RUN mkdir -p ${REPO}; \
    cd ${REPO}; \
    LATEST_RUN=$(curl -s "https://api.github.com/repos/${OWNER}/${REPO}/actions/workflows/${WORKFLOW}/runs" | jq -r '.workflow_runs[0].id'); \
    curl -LO "https://nightly.link/${OWNER}/${REPO}/actions/runs/${LATEST_RUN}/debs.zip"; \
    unzip *.zip || exit 1; \
    apt-get install -y ./*.deb || exit 1; \
    rm -rf /tmp/${REPO}*;

# Clean up and remove package lists to reduce image size
RUN	apt-mark auto '.*' > /dev/null; \
	apt-mark manual stustapay >/dev/null; \
	[ -z "${PERM_PACKAGES}" ] || apt-mark manual ${PERM_PACKAGES} >/dev/null; \
	apt purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	rm -rf /var/lib/apt/lists/*;

# Reset the working directory to /
WORKDIR /

# Removing nginx default sites
RUN rm /etc/nginx/sites-enabled/*; \
	rm /etc/nginx/sites-available/*;


# Enabeling nginx configs
COPY docker/nginx/ /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/stustapay-* /etc/nginx/sites-enabled/;

# Copy smaple config and entrypoint script
COPY docker/config.yaml /etc/stustapay/config.yaml.template
COPY --chmod=744 docker/entrypoint.sh /usr/local/bin/

# Squashing Layers
#FROM scratch as squash
#COPY --from=base / /

# Environment variables for configuration
ENV DB_HOST="psql"
ENV DB_USER="stustapay"
ENV DB_PASS="stustapay"
ENV DB_NAME="stustapay"
ENV TEST_MODE=false
ENV SECRET_KEY="1q2w3e4r"
ENV ADMIN_SERVER_NAME="admin.my-ssp-domain"
ENV ADMIN_BASE_URL="http://localhost:8081/api"
ENV ADMIN_HOST="localhost"
ENV ADMIN_PORT=8081
ENV CUSTOMER_SERVER_NAME="customerportal.my-ssp-domain"
ENV CUSTOMER_BASE_URL="http://localhost:8082/api"
ENV CUSTOMER_HOST="localhost"
ENV CUSTOMER_PORT=8082
ENV TERMINAL_SERVER_NAME="terminal.my-ssp-domain"
ENV TERMINAL_BASE_URL="http://localhost:8083/api"
ENV TERMINAL_HOST="localhost"
ENV TERMINAL_PORT=8083

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Set CMD's
CMD [ "nginx", "stustapay administration-api", "stustapay customerportal-api", "stustapay terminalserver-api" ]

EXPOSE 8080 80/tcp
EXPOSE 8081 8081/tcp
EXPOSE 8082 8082/tcp
EXPOSE 8083 8083/tcp
```

Could you please review the provided information and let me know if there’s anything else needed to diagnose the issue?

Thank you for your assistance!

Best regards,  
MineTech13 | Nils Z.

**Comment by TheJJ** [comment]
i think the cause for the error is that the customer portal couldn't fetch the config, so you don't have a currency configuration and the browser api complains because of that.

`https://cp.ssp.minescripts.me/api/config?base_url=https%3A%2F%2Fcp.ssp.minescripts.me` should return a valid config, what does the customerportal webserver say when one opens this url?

**Comment by TheJJ** [comment]
I've opened #396 that should take care of better handling the error.
Out of curiosity, what for do you want to use SSP?

**Comment by MineTech13** [comment]
OHHHHHHHHHH, I totally overlooked that! I didn’t realize the base URL needed to be set in the event configuration.

I was beginning to wonder if my config.yaml was incorrect. My bad!

Thank you so much for the help and pointing me in the right direction. I really appreciate it!

Regarding your question, we want to use the cashless pay feature of the system for our convention ^^. This will help us decrease the number of SumUp terminals and cash registers we need to hand out and stock up otherwise. We are also currently checking out if it would be a feasible idea to use NFC tags as our con badges, which then would be used for this system, or possibly wristbands.

Best regards,
MineTech13 | Nils Z.

**Comment by TheJJ** [comment]
Sounds like a perfect use-case! What convention is it? What NFC Scanners/telephones will you use?
Getting the NFC programming right is tricky, let's see what your experience will be :)
